### PR TITLE
Add tz_aware to configuration variables

### PR DESCRIPTION
**Pull request by jbenito3**
I have added a new configuration variable so one can set the MongoDB connection to be timezone aware. This is very handy for cases in which we need to deal with datetimes from different timezones.

### CODE REVIEW

**Comment by jarus** [comment]
Nice feature. We should only look that all tests passed.

**Comment by jarus** [comment]
Sorry the tests are failed because of issue #16.

**Comment by jarus** [comment]
I rebased and merged your commit into master.
Thank you for this nice change. :+1:

Ref: 79457840afa3d88743cea6d6b59526017ea3834a

**Comment by jbenito3** [comment]
Great! Thanks!

**Pull request closed without merging**
